#!/bin/bash

POSTGRES_VERSION=15.1.0

DATABASE_SERVER_HOST=192.168.56.30
DATABASE_SERVER_PORT=35432
DATABASE_USER=idp
DATABASE_NAME=idp

docker run -it --rm --name psql bitnami/postgresql:$POSTGRES_VERSION psql -h $DATABASE_SERVER_HOST -p $DATABASE_SERVER_PORT -U $DATABASE_USER -d $DATABASE_NAME
