version: "3.8"

services:
  nfs:
    image: erichough/nfs-server:2.2.1
    container_name: idp.dev.nfs-server
    environment:
    - NFS_EXPORT_0=/kubernetes/volumes *(rw,fsid=0,sync,no_subtree_check,no_root_squash,no_all_squash,insecure,no_auth_nlm)
    - NFS_DISABLE_VERSION_3=true
    - NFS_LOG_LEVEL=DEBUG
    volumes:
    - nfs-volume:/kubernetes/volumes
    ports:
    - 2049:2049
    cap_add:
    - SYS_ADMIN
networks:
  default:
    name: idp.dev.nfs-network
volumes:
  nfs-volume:
    name: idp.dev.nfs-volume
