spring:
  profiles:
    active: "dev"
  datasource:
    url: "jdbc:postgresql://192.168.56.30:35432/idp"
    username: "idp"
    password: "idp"
    hikari:
      initialization-fail-timeout: -1
  jpa:
    hibernate:
      ddl-auto: "none"
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true

server:
  port: 8080

management:
  server:
    port: 8888
  endpoints:
    web:
      base-path: "/management"
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "ALWAYS"
      show-components: "ALWAYS"
