name: Source Code CI

on:
  push:
    branches:
    - main
    paths:
    - src/**
  pull_request:
    branches:
    - main
    paths:
    - src/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build
      run: mvn package --file=./src/pom.xml -DskipTests
  quality-analysis:
    name: Quality Analysis
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run tests & analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarcloud.io
        SONAR_ORGANIZATION: ${{ github.repository_owner }}
        SONAR_PROJECT_KEY: ${{ github.repository_owner }}_${{ github.event.repository.name }}
      run: >
        mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        -Pquality-analysis
        -Dsonar.host.url=$SONAR_HOST_URL
        -Dsonar.organization=$SONAR_ORGANIZATION
        -Dsonar.projectKey=$SONAR_PROJECT_KEY
        --file=./src/pom.xml
