# -*- mode: ruby -*-
# vi: set ft=ruby :


PROJECT_NAME                  = "idp"
ENVIRONMENT_NAME              = "dev"

MASTER_NODE_BASENAME          = "master"
WORKER_NODE_BASENAME          = "worker"

NODES_CIDR                    = "192.168.56."
NODES_IP_START                = 28

POD_NETWORK_CIDR              = "172.16.0.0/12"

PROVISIONING_SCRIPTS_BASEPATH = "./scripts/"
COMMON_PROVISIONING_SCRIPT    = PROVISIONING_SCRIPTS_BASEPATH + "common.sh"
MASTER_PROVISIONING_SCRIPT    = PROVISIONING_SCRIPTS_BASEPATH + "master.sh"
WORKER_PROVISIONING_SCRIPT    = PROVISIONING_SCRIPTS_BASEPATH + "worker.sh"

NODES_CONFIG                  = [
  { :name => MASTER_NODE_BASENAME + "-01", :ip => NODES_CIDR + "#{NODES_IP_START + 1}", :cpus => 2, :memory => 2048, :provisioning_script => MASTER_PROVISIONING_SCRIPT },
  { :name => WORKER_NODE_BASENAME + "-01", :ip => NODES_CIDR + "#{NODES_IP_START + 2}", :cpus => 1, :memory => 1024, :provisioning_script => WORKER_PROVISIONING_SCRIPT },
  { :name => WORKER_NODE_BASENAME + "-02", :ip => NODES_CIDR + "#{NODES_IP_START + 3}", :cpus => 1, :memory => 1024, :provisioning_script => WORKER_PROVISIONING_SCRIPT }
]

HOSTS                         = NODES_CONFIG.map{|node_config| node_config[:ip] + ":" + node_config[:name]}.join(",")

MASTER_IP                     = NODES_CONFIG.find{|node_config| node_config[:name].start_with? MASTER_NODE_BASENAME}[:ip]


Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-22.04"
  config.vm.box_check_update = true

  NODES_CONFIG.each do |node_config|

    config.vm.define node_config[:name] do |node|

      node.vm.provider "virtualbox" do |vb|
        vb.name = PROJECT_NAME + "." + ENVIRONMENT_NAME + "." + node_config[:name]
        vb.cpus = node_config[:cpus]
        vb.memory = node_config[:memory]
      end

      node.vm.hostname = node_config[:name]
      node.vm.network "private_network", ip: node_config[:ip]

      node.vm.provision "shell", path: COMMON_PROVISIONING_SCRIPT, :args => "--hosts=#{HOSTS}"

      node.vm.provision :shell do |shell|
        shell.privileged = true
        shell.inline = "echo Rebooting #{node_config[:name]}..."
        shell.reboot = true
      end

      node.vm.provision "shell", path: node_config[:provisioning_script], :args => "--master-ip=#{MASTER_IP} --pod-network-cidr=#{POD_NETWORK_CIDR}"

    end

  end

end
